swagger: "2.0"
info:
  description: "To Do List"
  version: "1.0.0"
  title: "Swagger Petstore"

paths:

  /task/new:
    post:
      description: Returns all pets from the system that the user has access to
      produces:
      - application/json
      responses:
        '200':
          description: A list of pets.
          
  
